name = "Aetheria"
author = "Tostadora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "202f40d35c7e30c7ab4a26ae543adccfdad1edfc936429d982bcb98ecb83e58a"

[versions]
minecraft = "1.21.1"
quilt = "0.30.0-beta.7"

[options]
acceptable-game-versions = ["1.21", "1.21.2"]
