#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Apr 13 10:37:16 BOT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=6
shaderPack=\u00A7lE-LITE shaders 5.0.1.zip
